### ISSUE TITLE
Q regarding mapping

### ISSUE THREAD

**Issue by aistBMRG** [WatsonLab/single_and_multiple_binning#1]
Thanks for this study -- very useful in clarifying some ongoing issues/discussions.

Now, would it be possible to clarify the following? For the multi-coverage mapping, am I correct in understanding that your strategy involves mapping reads from individual samples to contigs from all samples separately? For example, 10 samples would yield 10 contig sets and then we would need to perform 10x10 mappings?

Or is mapping performed to the combined contigs from all samples, as is implemented in the VAMB workflow? In the case of 10 samples, we would then need to perform 10 mappings.

As an aside, I would imagine that reads would map best to their corresponding contigs, and less to contigs from other samples. Does you workflow consider that, or are all mappings handled equivalently, or is there some kind of weighing (for a given sample, given more weight to abundances estimated using the reads that generated these contigs)? Sorry, may be somewhat confusing but somewhat hard to articulate ...

Thanks in advance.

Dieter

**Comment by mw55309** [comment]
`Now, would it be possible to clarify the following? For the multi-coverage mapping, am I correct in understanding that your strategy involves mapping reads from individual samples to contigs from all samples separately? For example, 10 samples would yield 10 contig sets and then we would need to perform 10x10 mappings?`

Yes

`Or is mapping performed to the combined contigs from all samples, as is implemented in the VAMB workflow? In the case of 10 samples, we would then need to perform 10 mappings.`

My instinct here is that by doing this, you would create a multi-mapping problem, and some contigs would become invisible. But I have not shown this (yet)

`As an aside, I would imagine that reads would map best to their corresponding contigs, and less to contigs from other samples. Does you workflow consider that, or are all mappings handled equivalently, or is there some kind of weighing (for a given sample, given more weight to abundances estimated using the reads that generated these contigs)? Sorry, may be somewhat confusing but somewhat hard to articulate ...`

I understand what you mean! Not in this research, no weighting is applied, but of course this is something one could consider

**Comment by aistBMRG** [comment]
Hi Mick,

Thanks for taking the time to respond and clarify -- I understand. For the mapping to the combined contigs, I agree, it seems reasonable to expect some type of multi-mapping issues; maybe this could be resolved by estimating abundances based on expectation maximization to handle these, as is in done in Kallisto -- not sure though ...

Best,

Dieter
