### ISSUE TITLE
Binning after combining coverage (Multi-coverage)

### ISSUE THREAD

**Issue by FelipeMSD** [WatsonLab/single_and_multiple_binning#2]
Dear all,

I'm testing a NF pipeline based on this Snakelike pipeline with 3 samples, however, after I run `metabat2 --minContig 2500 -t 8 -i ERR11269024.fasta -a ERR11269024.txt --unbinned -o ERR11269024/ERR11269024` I receive the following message: `[Error!] Number of columns (excluding the first column) in abundance data file is not even.`. I know that my file `ERR11269024.txt` has 8 columns (excluding the first column), as you can see [here](https://drive.google.com/file/d/1WFybR7jr52sgDNgpjLt4fhQ5c62yDTeh/view?usp=sharing). What might I be doing wrong? Is the combined_coverage file `ERR11269024.txt` supposed to have this format?

Kind regards,
Felipe

**Comment by mw55309** [comment]
Hey!

So you have the right number of column headings, but row 1 has only two of six entries and row 2 has a different two of siz entries.

My recommendation would be to fix this and see if it solves the problem :)

Cheers
Mick

**Comment by mw55309** [comment]
I also see you have contigs from multiple assemblies in there - so I think you are joining the wrong coverage tables together

**Comment by FelipeMSD** [comment]
All right. Let me take a look again. Thanks!

**Comment by FelipeMSD** [comment]
Now I saw the problem... I inverted the ids and was concatenating coverage files based on the fastq files IDs instead of the assemblies. Thank you very much and sorry for the inconvinience. Now it worked very well! I'm anxious to get the results of that!
